rule_1_triggers = ['promote','inhibit','induce','suppress','increase','decrease','upregulate','downregulate',
                  'up-regulate','down-regulate','elevate','reduce','overexpress','underexpress','over-express',
                   'under-express','amplify','support','facilitate','hinder', 'boost', 'alleviate',
                   'accelerate', 'enhance', 'attenuate', 'activate', 'stimulate', 'improve'
                   ]

rule_2_effect_triggers = ['promotion','inhibition','suppression','increase','decrease','upregulation',
                   'downregulation','up-regulation','down-regulation','elevation','reduction','overexpression',
                   'underexpression','over-expression','under-expression','amplification','positive-regulation',
                    'negative-regulation', 'silencing', 'knockdown', 'deletion', 'silence', 'delete']

rule_2_verb_triggers = ['promote','induce','cause','aid','assist','boost','support','help','facilitate',
                        'hinder','enhance', 'boost','alleviate']

rule_3_triggers = ['activator','promoter','supressor','inhibitor','upregulator','up-regulator','downregulator',
                  'down-regulator', 'booster', 'supporter']

relation_triggers = {
    'promote' : 'positive',
    'inhibit' : 'negative',
    'induce' : 'positive',
    'suppress' : 'negative',
    'increase' : 'positive',
    'decrease' : 'negative',
    'upregulate' : 'positive',
    'downregulate' : 'negative',
    'up-regulate' : 'positive',
    'down-regulate' : 'negative',
    'elevate' : 'positive',
    'reduce' : 'negative',
    'overexpress' : 'positive',
    'underexpress' : 'negative',
    'over-express' : 'positive',
    'under-express' : 'negative',
    'amplify' : 'positive',
    'support' : 'positive',
    'facilitate' : 'positive',
    'hinder' : 'negative', 
    'promotion' : 'positive',
    'inhibition' : 'negative',
    'suppression' : 'negative',
    'increase' : 'positive',
    'decrease' : 'negative',
    'upregulation' : 'positive',
    'downregulation' : 'negative',
    'up-regulation' : 'positive',
    'down-regulation' : 'negative',
    'elevation' : 'positive',
    'reduction' : 'negative',
    'overexpression' : 'positive',
    'underexpression' : 'negative',
    'over-expression' : 'positive',
    'under-expression' : 'negative',
    'amplification' : 'positive',
    'positive-regulation' : 'positive',
    'negative-regulation': 'negative',
    'activator' : 'positive',
    'promoter' : 'positive',
    'supressor' : 'negative',
    'inhibitor' : 'positive',
    'upregulator' : 'positive',
    'up-regulator' : 'positive',
    'downregulator' : 'negative',
    'down-regulator' : 'negative', 
    'booster' : 'positive', 
    'supporter' : 'positive',
    'boost': 'positive',
    'alleviate': 'negative',
    'silencing': 'negative',
    'knockdown': 'negative',
    'deletion': 'negative',
    'silence': 'negative',
    'deleting': 'negative',
    'accelerate': 'positive',
    'enhance': 'positive',
    'attenuate': 'negative', 
    'activate': 'positive', 
    'stimulate': 'positive', 
    'improve': 'positive'
}

